require("nero_f.globals")
require("nero_f.set")
require("nero_f.keymap")
require("nero_f.packer")
require("nero_f.cmp")
require("nero_f.lsp")
require("nero_f.scheme")
require("nero_f.telescope")
require("nero_f.treesitter")
require("nero_f.seecrete")
-- require("nero_f.dressing")
require("nero_f.setup")
require("nero_f.plenary")
require("nero_f.dap")

